name: PinguLagerSystem
version: 1.0.0
main: de.pingu.lager.PinguLagerSystem
api-version: "1.21.4"
author: PinguinLars
depend: [Vault, PlotSquared]

commands:
  lager:
    description: Hauptbefehl für das LagerSystem
    usage: /<command> buy
    aliases: [ls]

permissions:
  pingulager.buy:
    description: Erlaubt das Kaufen eines LagerServers
    default: true
